# Generated by Django 5.0.7 on 2024-10-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaverde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='pendiente_de_entrega',
            field=models.BooleanField(default=True),
        ),
    ]
