# Generated by Django 5.0.7 on 2024-10-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaverde', '0002_carrito_pendiente_de_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
